# Generated by Django 4.2.7 on 2023-12-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, default=None, upload_to='portfolio/videos/'),
            preserve_default=False,
        ),
    ]
