# Generated by Django 4.2.7 on 2023-12-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
    ]
