# Generated by Django 4.2.7 on 2023-12-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_pinza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pinza',
        ),
    ]
